# fly.toml file generated for wizdle on 2022-10-28T15:38:06-06:00

app = "wizdle"
primary_region = "dfw"

[env]
PORT = "8080"

[http_service]
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true

[http_service.concurrency]
type = "requests"
hard_limit = 500
soft_limit = 200
